# Generated by Django 6.0.2 on 2026-02-26 16:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instructor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان دوره')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('overview', models.TextField(verbose_name='بررسی اجمالی')),
                ('curriculum', models.TextField(verbose_name='برنامه تحصیلی')),
                ('image', models.ImageField(upload_to='courses/', verbose_name='تصویر دوره')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='هزینه دوره')),
                ('duration_hours', models.PositiveIntegerField(verbose_name='ساعت دوره')),
                ('total_lectures', models.PositiveIntegerField(verbose_name='کل سخنرانی\u200cها')),
                ('capacity', models.PositiveIntegerField(verbose_name='تعداد صندلی\u200cها')),
                ('students_count', models.PositiveIntegerField(default=0, verbose_name='کل دانش\u200cآموزان')),
                ('has_certificate', models.BooleanField(choices=[(True, 'بله'), (False, 'خیر')], default=False, verbose_name='گواهینامه دارد؟')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.category', verbose_name='دسته بندی')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='instructor.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='امتیاز')),
                ('approved', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
