# Generated by Django 6.0.2 on 2026-02-26 20:50

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_instructor_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل '),
        ),
        migrations.AddField(
            model_name='instructor',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='IR', verbose_name='شماره تماس'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس سایت'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='image',
            field=models.ImageField(upload_to='instructors/', verbose_name='عکس'),
        ),
    ]
