# Generated by Django 6.0.2 on 2026-02-22 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='counted_view',
            new_name='counted_views',
        ),
    ]
