# Generated by Django 6.0.2 on 2026-02-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_category_slug_remove_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'دانشجو'), ('teacher', 'استاد')], default='student', max_length=10),
        ),
    ]
